### ISSUE TITLE
사진을 추가해도 빨간색 아이콘으로만 뜹니다

### ISSUE THREAD

**Issue by mcpejs** [RyuaNerin/Kisbo#8]
윈도우10이고 닷넷 프레임워크 4.0이 설치되어있습니다.
![image](https://user-images.githubusercontent.com/15870158/91649233-bfb7f500-eaac-11ea-9e86-62718bf483e6.png)
이 720x479 고양이 사진을 
관리자권한으로도 추가 해보고 그냥도 추가 해봤지만
 
![image](https://user-images.githubusercontent.com/15870158/91649272-11607f80-eaad-11ea-9aa6-beaefcb64137.png)
이렇게 화살표가 떠있다가 잠시뒤에

![image](https://user-images.githubusercontent.com/15870158/91649287-3bb23d00-eaad-11ea-9a88-848f0de8ce87.png)
![image](https://user-images.githubusercontent.com/15870158/91649280-2806d680-eaad-11ea-8707-fb739c235f8c.png)
이렇게 알림과함께 상태가 빨간 동그라미로 변합니다.
이제 이 프로그램은 작동이 불가능한건가요?

**Comment by RyuaNerin** [comment]
확인해보겠습니다.

**Comment by RyuaNerin** [comment]
[`0.0.0.17`](https://github.com/RyuaNerin/Kisbo/releases/tag/0.0.0.17) 에서 수정했습니다.
